// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/config.proto

package io.ncraft.ncraft.messaging;

public final class ConfigProto {
  private ConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ncraft/messaging/config.proto\022\020ncraft." +
      "messaging\032#ncraft/messaging/subscription" +
      ".proto\"w\n\006Config\022\020\n\010provider\030\001 \001(\t\022\016\n\006br" +
      "oker\030\002 \001(\t\022\024\n\014service_name\030\003 \001(\t\0225\n\rsubs" +
      "criptions\030\n \003(\0132\036.ncraft.messaging.Subsc" +
      "riptionBj\n\032io.ncraft.ncraft.messagingB\013C" +
      "onfigProtoP\001Z=github.com/ncraft-io/ncraf" +
      "t/go/pkg/ncraft/messaging;messagingb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.ncraft.ncraft.messaging.SubscriptionProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_Config_descriptor,
        new java.lang.String[] { "Provider", "Broker", "ServiceName", "Subscriptions", });
    io.ncraft.ncraft.messaging.SubscriptionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
