// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/config.proto

package io.ncraft.ncraft.messaging;

/**
 * Protobuf type {@code ncraft.messaging.Config}
 */
public final class Config extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ncraft.messaging.Config)
    ConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Config() {
    provider_ = "";
    broker_ = "";
    serviceName_ = "";
    subscriptions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Config();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.ncraft.messaging.ConfigProto.internal_static_ncraft_messaging_Config_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.ncraft.messaging.ConfigProto.internal_static_ncraft_messaging_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.ncraft.messaging.Config.class, io.ncraft.ncraft.messaging.Config.Builder.class);
  }

  public static final int PROVIDER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object provider_ = "";
  /**
   * <code>string provider = 1;</code>
   * @return The provider.
   */
  @java.lang.Override
  public java.lang.String getProvider() {
    java.lang.Object ref = provider_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      provider_ = s;
      return s;
    }
  }
  /**
   * <code>string provider = 1;</code>
   * @return The bytes for provider.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProviderBytes() {
    java.lang.Object ref = provider_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      provider_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BROKER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object broker_ = "";
  /**
   * <code>string broker = 2;</code>
   * @return The broker.
   */
  @java.lang.Override
  public java.lang.String getBroker() {
    java.lang.Object ref = broker_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      broker_ = s;
      return s;
    }
  }
  /**
   * <code>string broker = 2;</code>
   * @return The bytes for broker.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrokerBytes() {
    java.lang.Object ref = broker_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      broker_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceName_ = "";
  /**
   * <code>string service_name = 3;</code>
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }
  /**
   * <code>string service_name = 3;</code>
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBSCRIPTIONS_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private java.util.List<io.ncraft.ncraft.messaging.Subscription> subscriptions_;
  /**
   * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
   */
  @java.lang.Override
  public java.util.List<io.ncraft.ncraft.messaging.Subscription> getSubscriptionsList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.ncraft.ncraft.messaging.SubscriptionOrBuilder> 
      getSubscriptionsOrBuilderList() {
    return subscriptions_;
  }
  /**
   * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
   */
  @java.lang.Override
  public int getSubscriptionsCount() {
    return subscriptions_.size();
  }
  /**
   * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
   */
  @java.lang.Override
  public io.ncraft.ncraft.messaging.Subscription getSubscriptions(int index) {
    return subscriptions_.get(index);
  }
  /**
   * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
   */
  @java.lang.Override
  public io.ncraft.ncraft.messaging.SubscriptionOrBuilder getSubscriptionsOrBuilder(
      int index) {
    return subscriptions_.get(index);
  }

  public static final int NATS_FIELD_NUMBER = 15;
  private io.ncraft.ncraft.messaging.Nats nats_;
  /**
   * <code>.ncraft.messaging.Nats nats = 15;</code>
   * @return Whether the nats field is set.
   */
  @java.lang.Override
  public boolean hasNats() {
    return nats_ != null;
  }
  /**
   * <code>.ncraft.messaging.Nats nats = 15;</code>
   * @return The nats.
   */
  @java.lang.Override
  public io.ncraft.ncraft.messaging.Nats getNats() {
    return nats_ == null ? io.ncraft.ncraft.messaging.Nats.getDefaultInstance() : nats_;
  }
  /**
   * <code>.ncraft.messaging.Nats nats = 15;</code>
   */
  @java.lang.Override
  public io.ncraft.ncraft.messaging.NatsOrBuilder getNatsOrBuilder() {
    return nats_ == null ? io.ncraft.ncraft.messaging.Nats.getDefaultInstance() : nats_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(provider_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, provider_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(broker_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, broker_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceName_);
    }
    for (int i = 0; i < subscriptions_.size(); i++) {
      output.writeMessage(10, subscriptions_.get(i));
    }
    if (nats_ != null) {
      output.writeMessage(15, getNats());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(provider_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, provider_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(broker_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, broker_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceName_);
    }
    for (int i = 0; i < subscriptions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, subscriptions_.get(i));
    }
    if (nats_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getNats());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.ncraft.messaging.Config)) {
      return super.equals(obj);
    }
    io.ncraft.ncraft.messaging.Config other = (io.ncraft.ncraft.messaging.Config) obj;

    if (!getProvider()
        .equals(other.getProvider())) return false;
    if (!getBroker()
        .equals(other.getBroker())) return false;
    if (!getServiceName()
        .equals(other.getServiceName())) return false;
    if (!getSubscriptionsList()
        .equals(other.getSubscriptionsList())) return false;
    if (hasNats() != other.hasNats()) return false;
    if (hasNats()) {
      if (!getNats()
          .equals(other.getNats())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROVIDER_FIELD_NUMBER;
    hash = (53 * hash) + getProvider().hashCode();
    hash = (37 * hash) + BROKER_FIELD_NUMBER;
    hash = (53 * hash) + getBroker().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    if (getSubscriptionsCount() > 0) {
      hash = (37 * hash) + SUBSCRIPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionsList().hashCode();
    }
    if (hasNats()) {
      hash = (37 * hash) + NATS_FIELD_NUMBER;
      hash = (53 * hash) + getNats().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.ncraft.messaging.Config parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.ncraft.messaging.Config prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ncraft.messaging.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ncraft.messaging.Config)
      io.ncraft.ncraft.messaging.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.ncraft.messaging.ConfigProto.internal_static_ncraft_messaging_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.ncraft.messaging.ConfigProto.internal_static_ncraft_messaging_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.ncraft.messaging.Config.class, io.ncraft.ncraft.messaging.Config.Builder.class);
    }

    // Construct using io.ncraft.ncraft.messaging.Config.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      provider_ = "";
      broker_ = "";
      serviceName_ = "";
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
      } else {
        subscriptions_ = null;
        subscriptionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      nats_ = null;
      if (natsBuilder_ != null) {
        natsBuilder_.dispose();
        natsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.ncraft.messaging.ConfigProto.internal_static_ncraft_messaging_Config_descriptor;
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.Config getDefaultInstanceForType() {
      return io.ncraft.ncraft.messaging.Config.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.Config build() {
      io.ncraft.ncraft.messaging.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.Config buildPartial() {
      io.ncraft.ncraft.messaging.Config result = new io.ncraft.ncraft.messaging.Config(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.ncraft.ncraft.messaging.Config result) {
      if (subscriptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          subscriptions_ = java.util.Collections.unmodifiableList(subscriptions_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.subscriptions_ = subscriptions_;
      } else {
        result.subscriptions_ = subscriptionsBuilder_.build();
      }
    }

    private void buildPartial0(io.ncraft.ncraft.messaging.Config result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.provider_ = provider_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.broker_ = broker_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serviceName_ = serviceName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.nats_ = natsBuilder_ == null
            ? nats_
            : natsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.ncraft.messaging.Config) {
        return mergeFrom((io.ncraft.ncraft.messaging.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.ncraft.messaging.Config other) {
      if (other == io.ncraft.ncraft.messaging.Config.getDefaultInstance()) return this;
      if (!other.getProvider().isEmpty()) {
        provider_ = other.provider_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBroker().isEmpty()) {
        broker_ = other.broker_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (subscriptionsBuilder_ == null) {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptions_.isEmpty()) {
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSubscriptionsIsMutable();
            subscriptions_.addAll(other.subscriptions_);
          }
          onChanged();
        }
      } else {
        if (!other.subscriptions_.isEmpty()) {
          if (subscriptionsBuilder_.isEmpty()) {
            subscriptionsBuilder_.dispose();
            subscriptionsBuilder_ = null;
            subscriptions_ = other.subscriptions_;
            bitField0_ = (bitField0_ & ~0x00000008);
            subscriptionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubscriptionsFieldBuilder() : null;
          } else {
            subscriptionsBuilder_.addAllMessages(other.subscriptions_);
          }
        }
      }
      if (other.hasNats()) {
        mergeNats(other.getNats());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              provider_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              broker_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              serviceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 82: {
              io.ncraft.ncraft.messaging.Subscription m =
                  input.readMessage(
                      io.ncraft.ncraft.messaging.Subscription.parser(),
                      extensionRegistry);
              if (subscriptionsBuilder_ == null) {
                ensureSubscriptionsIsMutable();
                subscriptions_.add(m);
              } else {
                subscriptionsBuilder_.addMessage(m);
              }
              break;
            } // case 82
            case 122: {
              input.readMessage(
                  getNatsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object provider_ = "";
    /**
     * <code>string provider = 1;</code>
     * @return The provider.
     */
    public java.lang.String getProvider() {
      java.lang.Object ref = provider_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        provider_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string provider = 1;</code>
     * @return The bytes for provider.
     */
    public com.google.protobuf.ByteString
        getProviderBytes() {
      java.lang.Object ref = provider_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        provider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider = 1;</code>
     * @param value The provider to set.
     * @return This builder for chaining.
     */
    public Builder setProvider(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      provider_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string provider = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvider() {
      provider_ = getDefaultInstance().getProvider();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string provider = 1;</code>
     * @param value The bytes for provider to set.
     * @return This builder for chaining.
     */
    public Builder setProviderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      provider_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object broker_ = "";
    /**
     * <code>string broker = 2;</code>
     * @return The broker.
     */
    public java.lang.String getBroker() {
      java.lang.Object ref = broker_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        broker_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string broker = 2;</code>
     * @return The bytes for broker.
     */
    public com.google.protobuf.ByteString
        getBrokerBytes() {
      java.lang.Object ref = broker_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        broker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string broker = 2;</code>
     * @param value The broker to set.
     * @return This builder for chaining.
     */
    public Builder setBroker(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      broker_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string broker = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBroker() {
      broker_ = getDefaultInstance().getBroker();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string broker = 2;</code>
     * @param value The bytes for broker to set.
     * @return This builder for chaining.
     */
    public Builder setBrokerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      broker_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 3;</code>
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_name = 3;</code>
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_name = 3;</code>
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      serviceName_ = getDefaultInstance().getServiceName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string service_name = 3;</code>
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<io.ncraft.ncraft.messaging.Subscription> subscriptions_ =
      java.util.Collections.emptyList();
    private void ensureSubscriptionsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        subscriptions_ = new java.util.ArrayList<io.ncraft.ncraft.messaging.Subscription>(subscriptions_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.ncraft.ncraft.messaging.Subscription, io.ncraft.ncraft.messaging.Subscription.Builder, io.ncraft.ncraft.messaging.SubscriptionOrBuilder> subscriptionsBuilder_;

    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public java.util.List<io.ncraft.ncraft.messaging.Subscription> getSubscriptionsList() {
      if (subscriptionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subscriptions_);
      } else {
        return subscriptionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public int getSubscriptionsCount() {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.size();
      } else {
        return subscriptionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public io.ncraft.ncraft.messaging.Subscription getSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);
      } else {
        return subscriptionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder setSubscriptions(
        int index, io.ncraft.ncraft.messaging.Subscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder setSubscriptions(
        int index, io.ncraft.ncraft.messaging.Subscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.set(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder addSubscriptions(io.ncraft.ncraft.messaging.Subscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder addSubscriptions(
        int index, io.ncraft.ncraft.messaging.Subscription value) {
      if (subscriptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, value);
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder addSubscriptions(
        io.ncraft.ncraft.messaging.Subscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder addSubscriptions(
        int index, io.ncraft.ncraft.messaging.Subscription.Builder builderForValue) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.add(index, builderForValue.build());
        onChanged();
      } else {
        subscriptionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder addAllSubscriptions(
        java.lang.Iterable<? extends io.ncraft.ncraft.messaging.Subscription> values) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subscriptions_);
        onChanged();
      } else {
        subscriptionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder clearSubscriptions() {
      if (subscriptionsBuilder_ == null) {
        subscriptions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        subscriptionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public Builder removeSubscriptions(int index) {
      if (subscriptionsBuilder_ == null) {
        ensureSubscriptionsIsMutable();
        subscriptions_.remove(index);
        onChanged();
      } else {
        subscriptionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public io.ncraft.ncraft.messaging.Subscription.Builder getSubscriptionsBuilder(
        int index) {
      return getSubscriptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public io.ncraft.ncraft.messaging.SubscriptionOrBuilder getSubscriptionsOrBuilder(
        int index) {
      if (subscriptionsBuilder_ == null) {
        return subscriptions_.get(index);  } else {
        return subscriptionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public java.util.List<? extends io.ncraft.ncraft.messaging.SubscriptionOrBuilder> 
         getSubscriptionsOrBuilderList() {
      if (subscriptionsBuilder_ != null) {
        return subscriptionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subscriptions_);
      }
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public io.ncraft.ncraft.messaging.Subscription.Builder addSubscriptionsBuilder() {
      return getSubscriptionsFieldBuilder().addBuilder(
          io.ncraft.ncraft.messaging.Subscription.getDefaultInstance());
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public io.ncraft.ncraft.messaging.Subscription.Builder addSubscriptionsBuilder(
        int index) {
      return getSubscriptionsFieldBuilder().addBuilder(
          index, io.ncraft.ncraft.messaging.Subscription.getDefaultInstance());
    }
    /**
     * <code>repeated .ncraft.messaging.Subscription subscriptions = 10;</code>
     */
    public java.util.List<io.ncraft.ncraft.messaging.Subscription.Builder> 
         getSubscriptionsBuilderList() {
      return getSubscriptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.ncraft.ncraft.messaging.Subscription, io.ncraft.ncraft.messaging.Subscription.Builder, io.ncraft.ncraft.messaging.SubscriptionOrBuilder> 
        getSubscriptionsFieldBuilder() {
      if (subscriptionsBuilder_ == null) {
        subscriptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.ncraft.ncraft.messaging.Subscription, io.ncraft.ncraft.messaging.Subscription.Builder, io.ncraft.ncraft.messaging.SubscriptionOrBuilder>(
                subscriptions_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        subscriptions_ = null;
      }
      return subscriptionsBuilder_;
    }

    private io.ncraft.ncraft.messaging.Nats nats_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ncraft.ncraft.messaging.Nats, io.ncraft.ncraft.messaging.Nats.Builder, io.ncraft.ncraft.messaging.NatsOrBuilder> natsBuilder_;
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     * @return Whether the nats field is set.
     */
    public boolean hasNats() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     * @return The nats.
     */
    public io.ncraft.ncraft.messaging.Nats getNats() {
      if (natsBuilder_ == null) {
        return nats_ == null ? io.ncraft.ncraft.messaging.Nats.getDefaultInstance() : nats_;
      } else {
        return natsBuilder_.getMessage();
      }
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public Builder setNats(io.ncraft.ncraft.messaging.Nats value) {
      if (natsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nats_ = value;
      } else {
        natsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public Builder setNats(
        io.ncraft.ncraft.messaging.Nats.Builder builderForValue) {
      if (natsBuilder_ == null) {
        nats_ = builderForValue.build();
      } else {
        natsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public Builder mergeNats(io.ncraft.ncraft.messaging.Nats value) {
      if (natsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          nats_ != null &&
          nats_ != io.ncraft.ncraft.messaging.Nats.getDefaultInstance()) {
          getNatsBuilder().mergeFrom(value);
        } else {
          nats_ = value;
        }
      } else {
        natsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public Builder clearNats() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nats_ = null;
      if (natsBuilder_ != null) {
        natsBuilder_.dispose();
        natsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public io.ncraft.ncraft.messaging.Nats.Builder getNatsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getNatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    public io.ncraft.ncraft.messaging.NatsOrBuilder getNatsOrBuilder() {
      if (natsBuilder_ != null) {
        return natsBuilder_.getMessageOrBuilder();
      } else {
        return nats_ == null ?
            io.ncraft.ncraft.messaging.Nats.getDefaultInstance() : nats_;
      }
    }
    /**
     * <code>.ncraft.messaging.Nats nats = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ncraft.ncraft.messaging.Nats, io.ncraft.ncraft.messaging.Nats.Builder, io.ncraft.ncraft.messaging.NatsOrBuilder> 
        getNatsFieldBuilder() {
      if (natsBuilder_ == null) {
        natsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ncraft.ncraft.messaging.Nats, io.ncraft.ncraft.messaging.Nats.Builder, io.ncraft.ncraft.messaging.NatsOrBuilder>(
                getNats(),
                getParentForChildren(),
                isClean());
        nats_ = null;
      }
      return natsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ncraft.messaging.Config)
  }

  // @@protoc_insertion_point(class_scope:ncraft.messaging.Config)
  private static final io.ncraft.ncraft.messaging.Config DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.ncraft.messaging.Config();
  }

  public static io.ncraft.ncraft.messaging.Config getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Config>
      PARSER = new com.google.protobuf.AbstractParser<Config>() {
    @java.lang.Override
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Config> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.ncraft.messaging.Config getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

