// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/config.proto

package io.ncraft.ncraft.messaging;

public final class ConfigProto {
  private ConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_Nats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_Nats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ncraft/messaging/config.proto\022\020ncraft." +
      "messaging\032#ncraft/messaging/subscription" +
      ".proto\"\235\001\n\006Config\022\020\n\010provider\030\001 \001(\t\022\016\n\006b" +
      "roker\030\002 \001(\t\022\024\n\014service_name\030\003 \001(\t\0225\n\rsub" +
      "scriptions\030\n \003(\0132\036.ncraft.messaging.Subs" +
      "cription\022$\n\004nats\030\017 \001(\0132\026.ncraft.messagin" +
      "g.Nats\"R\n\004Nats\022\022\n\njet_stream\030\001 \001(\t\022\023\n\013to" +
      "pic_names\030\002 \003(\t\022\020\n\010max_msgs\030\003 \001(\003\022\017\n\007max" +
      "_age\030\004 \001(\003Bj\n\032io.ncraft.ncraft.messaging" +
      "B\013ConfigProtoP\001Z=github.com/ncraft-io/nc" +
      "raft/go/pkg/ncraft/messaging;messagingb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.ncraft.ncraft.messaging.SubscriptionProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_Config_descriptor,
        new java.lang.String[] { "Provider", "Broker", "ServiceName", "Subscriptions", "Nats", });
    internal_static_ncraft_messaging_Nats_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ncraft_messaging_Nats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_Nats_descriptor,
        new java.lang.String[] { "JetStream", "TopicNames", "MaxMsgs", "MaxAge", });
    io.ncraft.ncraft.messaging.SubscriptionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
