// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/config.proto

package io.ncraft.ncraft.messaging;

public interface NatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ncraft.messaging.Nats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jet_stream = 1;</code>
   * @return The jetStream.
   */
  java.lang.String getJetStream();
  /**
   * <code>string jet_stream = 1;</code>
   * @return The bytes for jetStream.
   */
  com.google.protobuf.ByteString
      getJetStreamBytes();

  /**
   * <code>repeated string topic_names = 2;</code>
   * @return A list containing the topicNames.
   */
  java.util.List<java.lang.String>
      getTopicNamesList();
  /**
   * <code>repeated string topic_names = 2;</code>
   * @return The count of topicNames.
   */
  int getTopicNamesCount();
  /**
   * <code>repeated string topic_names = 2;</code>
   * @param index The index of the element to return.
   * @return The topicNames at the given index.
   */
  java.lang.String getTopicNames(int index);
  /**
   * <code>repeated string topic_names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topicNames at the given index.
   */
  com.google.protobuf.ByteString
      getTopicNamesBytes(int index);
}
