// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/push_endpoint.proto

package io.ncraft.ncraft.messaging;

public final class PushEndpointProto {
  private PushEndpointProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_PushEndpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_PushEndpoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$ncraft/messaging/push_endpoint.proto\022\020" +
      "ncraft.messaging\032\023mojo/core/url.proto\"L\n" +
      "\014PushEndpoint\022\017\n\007service\030\001 \001(\t\022\016\n\006method" +
      "\030\002 \001(\t\022\033\n\003url\030\003 \001(\0132\016.mojo.core.UrlBp\n\032i" +
      "o.ncraft.ncraft.messagingB\021PushEndpointP" +
      "rotoP\001Z=github.com/ncraft-io/ncraft/go/p" +
      "kg/ncraft/messaging;messagingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.UrlProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_PushEndpoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_PushEndpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_PushEndpoint_descriptor,
        new java.lang.String[] { "Service", "Method", "Url", });
    org.mojolang.mojo.core.UrlProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
