// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/push_endpoint.proto

package io.ncraft.ncraft.messaging;

public interface PushEndpointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ncraft.messaging.PushEndpoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>.mojo.core.Url url = 3;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <code>.mojo.core.Url url = 3;</code>
   * @return The url.
   */
  org.mojolang.mojo.core.Url getUrl();
  /**
   * <code>.mojo.core.Url url = 3;</code>
   */
  org.mojolang.mojo.core.UrlOrBuilder getUrlOrBuilder();
}
