// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/received_message.proto

package io.ncraft.ncraft.messaging;

/**
 * Protobuf type {@code ncraft.messaging.ReceivedMessage}
 */
public final class ReceivedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ncraft.messaging.ReceivedMessage)
    ReceivedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReceivedMessage.newBuilder() to construct.
  private ReceivedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReceivedMessage() {
    id_ = "";
    data_ = "";
    ackId_ = "";
    subscription_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReceivedMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ncraft.ncraft.messaging.ReceivedMessage.class, io.ncraft.ncraft.messaging.ReceivedMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 2;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.mojolang.mojo.core.Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.mojolang.mojo.core.Value>newDefaultInstance(
                io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.mojolang.mojo.core.Value.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, org.mojolang.mojo.core.Value> attributes_;
  private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }
  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
   */
  @java.lang.Override
  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
   */
  @java.lang.Override
  public /* nullable */
org.mojolang.mojo.core.Value getAttributesOrDefault(
      java.lang.String key,
      /* nullable */
org.mojolang.mojo.core.Value defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Value getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object data_ = "";
  /**
   * <code>string data = 3;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACK_ID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ackId_ = "";
  /**
   * <code>string ack_id = 11;</code>
   * @return The ackId.
   */
  @java.lang.Override
  public java.lang.String getAckId() {
    java.lang.Object ref = ackId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ackId_ = s;
      return s;
    }
  }
  /**
   * <code>string ack_id = 11;</code>
   * @return The bytes for ackId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAckIdBytes() {
    java.lang.Object ref = ackId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ackId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBSCRIPTION_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subscription_ = "";
  /**
   * <code>string subscription = 12;</code>
   * @return The subscription.
   */
  @java.lang.Override
  public java.lang.String getSubscription() {
    java.lang.Object ref = subscription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subscription_ = s;
      return s;
    }
  }
  /**
   * <code>string subscription = 12;</code>
   * @return The bytes for subscription.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubscriptionBytes() {
    java.lang.Object ref = subscription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subscription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLISH_TIME_FIELD_NUMBER = 13;
  private org.mojolang.mojo.core.Timestamp publishTime_;
  /**
   * <code>.mojo.core.Timestamp publish_time = 13;</code>
   * @return Whether the publishTime field is set.
   */
  @java.lang.Override
  public boolean hasPublishTime() {
    return publishTime_ != null;
  }
  /**
   * <code>.mojo.core.Timestamp publish_time = 13;</code>
   * @return The publishTime.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Timestamp getPublishTime() {
    return publishTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : publishTime_;
  }
  /**
   * <code>.mojo.core.Timestamp publish_time = 13;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TimestampOrBuilder getPublishTimeOrBuilder() {
    return publishTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : publishTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        2);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ackId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, ackId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscription_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, subscription_);
    }
    if (publishTime_ != null) {
      output.writeMessage(13, getPublishTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (java.util.Map.Entry<java.lang.String, org.mojolang.mojo.core.Value> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.Value>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attributes__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ackId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, ackId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscription_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, subscription_);
    }
    if (publishTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getPublishTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ncraft.ncraft.messaging.ReceivedMessage)) {
      return super.equals(obj);
    }
    io.ncraft.ncraft.messaging.ReceivedMessage other = (io.ncraft.ncraft.messaging.ReceivedMessage) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!internalGetAttributes().equals(
        other.internalGetAttributes())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getAckId()
        .equals(other.getAckId())) return false;
    if (!getSubscription()
        .equals(other.getSubscription())) return false;
    if (hasPublishTime() != other.hasPublishTime()) return false;
    if (hasPublishTime()) {
      if (!getPublishTime()
          .equals(other.getPublishTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + ACK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAckId().hashCode();
    hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getSubscription().hashCode();
    if (hasPublishTime()) {
      hash = (37 * hash) + PUBLISH_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPublishTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ncraft.ncraft.messaging.ReceivedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ncraft.ncraft.messaging.ReceivedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ncraft.messaging.ReceivedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ncraft.messaging.ReceivedMessage)
      io.ncraft.ncraft.messaging.ReceivedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ncraft.ncraft.messaging.ReceivedMessage.class, io.ncraft.ncraft.messaging.ReceivedMessage.Builder.class);
    }

    // Construct using io.ncraft.ncraft.messaging.ReceivedMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      internalGetMutableAttributes().clear();
      data_ = "";
      ackId_ = "";
      subscription_ = "";
      publishTime_ = null;
      if (publishTimeBuilder_ != null) {
        publishTimeBuilder_.dispose();
        publishTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ncraft.ncraft.messaging.ReceivedMessageProto.internal_static_ncraft_messaging_ReceivedMessage_descriptor;
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.ReceivedMessage getDefaultInstanceForType() {
      return io.ncraft.ncraft.messaging.ReceivedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.ReceivedMessage build() {
      io.ncraft.ncraft.messaging.ReceivedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.ncraft.ncraft.messaging.ReceivedMessage buildPartial() {
      io.ncraft.ncraft.messaging.ReceivedMessage result = new io.ncraft.ncraft.messaging.ReceivedMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.ncraft.ncraft.messaging.ReceivedMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.attributes_ = internalGetAttributes();
        result.attributes_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.ackId_ = ackId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.subscription_ = subscription_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.publishTime_ = publishTimeBuilder_ == null
            ? publishTime_
            : publishTimeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ncraft.ncraft.messaging.ReceivedMessage) {
        return mergeFrom((io.ncraft.ncraft.messaging.ReceivedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ncraft.ncraft.messaging.ReceivedMessage other) {
      if (other == io.ncraft.ncraft.messaging.ReceivedMessage.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      bitField0_ |= 0x00000002;
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAckId().isEmpty()) {
        ackId_ = other.ackId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getSubscription().isEmpty()) {
        subscription_ = other.subscription_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasPublishTime()) {
        mergePublishTime(other.getPublishTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, org.mojolang.mojo.core.Value>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAttributes().getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 90: {
              ackId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 90
            case 98: {
              subscription_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getPublishTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, org.mojolang.mojo.core.Value> attributes_;
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
        internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.mojolang.mojo.core.Value>
        internalGetMutableAttributes() {
      if (attributes_ == null) {
        attributes_ = com.google.protobuf.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return attributes_;
    }
    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
org.mojolang.mojo.core.Value getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
org.mojolang.mojo.core.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public org.mojolang.mojo.core.Value getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearAttributes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.mojolang.mojo.core.Value>
        getMutableAttributes() {
      bitField0_ |= 0x00000002;
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        org.mojolang.mojo.core.Value value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>map&lt;string, .mojo.core.Value&gt; attributes = 2;</code>
     */
    public Builder putAllAttributes(
        java.util.Map<java.lang.String, org.mojolang.mojo.core.Value> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 3;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 3;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string data = 3;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object ackId_ = "";
    /**
     * <code>string ack_id = 11;</code>
     * @return The ackId.
     */
    public java.lang.String getAckId() {
      java.lang.Object ref = ackId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ackId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ack_id = 11;</code>
     * @return The bytes for ackId.
     */
    public com.google.protobuf.ByteString
        getAckIdBytes() {
      java.lang.Object ref = ackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ack_id = 11;</code>
     * @param value The ackId to set.
     * @return This builder for chaining.
     */
    public Builder setAckId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ackId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string ack_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAckId() {
      ackId_ = getDefaultInstance().getAckId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string ack_id = 11;</code>
     * @param value The bytes for ackId to set.
     * @return This builder for chaining.
     */
    public Builder setAckIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ackId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object subscription_ = "";
    /**
     * <code>string subscription = 12;</code>
     * @return The subscription.
     */
    public java.lang.String getSubscription() {
      java.lang.Object ref = subscription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subscription = 12;</code>
     * @return The bytes for subscription.
     */
    public com.google.protobuf.ByteString
        getSubscriptionBytes() {
      java.lang.Object ref = subscription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subscription = 12;</code>
     * @param value The subscription to set.
     * @return This builder for chaining.
     */
    public Builder setSubscription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subscription_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string subscription = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubscription() {
      subscription_ = getDefaultInstance().getSubscription();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string subscription = 12;</code>
     * @param value The bytes for subscription to set.
     * @return This builder for chaining.
     */
    public Builder setSubscriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subscription_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Timestamp publishTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> publishTimeBuilder_;
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     * @return Whether the publishTime field is set.
     */
    public boolean hasPublishTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     * @return The publishTime.
     */
    public org.mojolang.mojo.core.Timestamp getPublishTime() {
      if (publishTimeBuilder_ == null) {
        return publishTime_ == null ? org.mojolang.mojo.core.Timestamp.getDefaultInstance() : publishTime_;
      } else {
        return publishTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public Builder setPublishTime(org.mojolang.mojo.core.Timestamp value) {
      if (publishTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        publishTime_ = value;
      } else {
        publishTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public Builder setPublishTime(
        org.mojolang.mojo.core.Timestamp.Builder builderForValue) {
      if (publishTimeBuilder_ == null) {
        publishTime_ = builderForValue.build();
      } else {
        publishTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public Builder mergePublishTime(org.mojolang.mojo.core.Timestamp value) {
      if (publishTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          publishTime_ != null &&
          publishTime_ != org.mojolang.mojo.core.Timestamp.getDefaultInstance()) {
          getPublishTimeBuilder().mergeFrom(value);
        } else {
          publishTime_ = value;
        }
      } else {
        publishTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public Builder clearPublishTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      publishTime_ = null;
      if (publishTimeBuilder_ != null) {
        publishTimeBuilder_.dispose();
        publishTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public org.mojolang.mojo.core.Timestamp.Builder getPublishTimeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getPublishTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    public org.mojolang.mojo.core.TimestampOrBuilder getPublishTimeOrBuilder() {
      if (publishTimeBuilder_ != null) {
        return publishTimeBuilder_.getMessageOrBuilder();
      } else {
        return publishTime_ == null ?
            org.mojolang.mojo.core.Timestamp.getDefaultInstance() : publishTime_;
      }
    }
    /**
     * <code>.mojo.core.Timestamp publish_time = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder> 
        getPublishTimeFieldBuilder() {
      if (publishTimeBuilder_ == null) {
        publishTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Timestamp, org.mojolang.mojo.core.Timestamp.Builder, org.mojolang.mojo.core.TimestampOrBuilder>(
                getPublishTime(),
                getParentForChildren(),
                isClean());
        publishTime_ = null;
      }
      return publishTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ncraft.messaging.ReceivedMessage)
  }

  // @@protoc_insertion_point(class_scope:ncraft.messaging.ReceivedMessage)
  private static final io.ncraft.ncraft.messaging.ReceivedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ncraft.ncraft.messaging.ReceivedMessage();
  }

  public static io.ncraft.ncraft.messaging.ReceivedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReceivedMessage>
      PARSER = new com.google.protobuf.AbstractParser<ReceivedMessage>() {
    @java.lang.Override
    public ReceivedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReceivedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReceivedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.ncraft.ncraft.messaging.ReceivedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

