// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/received_message.proto

package io.ncraft.ncraft.messaging;

public final class ReceivedMessageProto {
  private ReceivedMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_ReceivedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_ReceivedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'ncraft/messaging/received_message.prot" +
      "o\022\020ncraft.messaging\032\023mojo/core/any.proto" +
      "\032\024mojo/core/time.proto\032\025mojo/core/value." +
      "proto\032\036ncraft/messaging/message.proto\"\231\002" +
      "\n\017ReceivedMessage\022\n\n\002id\030\001 \001(\t\022E\n\nattribu" +
      "tes\030\002 \003(\01321.ncraft.messaging.ReceivedMes" +
      "sage.AttributesEntry\022\034\n\004data\030\003 \001(\0132\016.moj" +
      "o.core.Any\022\016\n\006ack_id\030\013 \001(\t\022\024\n\014subscripti" +
      "on\030\014 \001(\t\022*\n\014publish_time\030\r \001(\0132\024.mojo.co" +
      "re.Timestamp\032C\n\017AttributesEntry\022\013\n\003key\030\001" +
      " \001(\t\022\037\n\005value\030\002 \001(\0132\020.mojo.core.Value:\0028" +
      "\001Bs\n\032io.ncraft.ncraft.messagingB\024Receive" +
      "dMessageProtoP\001Z=github.com/ncraft-io/nc" +
      "raft/go/pkg/ncraft/messaging;messagingb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.AnyProto.getDescriptor(),
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          io.ncraft.ncraft.messaging.MessageProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_ReceivedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_ReceivedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_ReceivedMessage_descriptor,
        new java.lang.String[] { "Id", "Attributes", "Data", "AckId", "Subscription", "PublishTime", });
    internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_descriptor =
      internal_static_ncraft_messaging_ReceivedMessage_descriptor.getNestedTypes().get(0);
    internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_ReceivedMessage_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    org.mojolang.mojo.core.AnyProto.getDescriptor();
    org.mojolang.mojo.core.TimeProto.getDescriptor();
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    io.ncraft.ncraft.messaging.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
