// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/subscription.proto

package io.ncraft.ncraft.messaging;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#ncraft/messaging/subscription.proto\022\020n" +
      "craft.messaging\032\024mojo/core/time.proto\032$n" +
      "craft/messaging/push_endpoint.proto\"\210\002\n\014" +
      "Subscription\022\014\n\004name\030\001 \001(\t\022\r\n\005topic\030\005 \001(" +
      "\t\022\r\n\005group\030\006 \001(\t\022\014\n\004pull\030\007 \001(\010\022\020\n\010auto_a" +
      "ck\030\t \001(\010\022(\n\013ack_timeout\030\n \001(\0132\023.mojo.cor" +
      "e.Duration\022\030\n\020pull_max_waiting\030\013 \001(\003\022\031\n\021" +
      "pending_msg_limit\030\014 \001(\003\022\033\n\023pending_bytes" +
      "_limit\030\r \001(\003\0220\n\010endpoint\030\017 \001(\0132\036.ncraft." +
      "messaging.PushEndpointBp\n\032io.ncraft.ncra" +
      "ft.messagingB\021SubscriptionProtoP\001Z=githu" +
      "b.com/ncraft-io/ncraft/go/pkg/ncraft/mes" +
      "saging;messagingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
          io.ncraft.ncraft.messaging.PushEndpointProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_Subscription_descriptor,
        new java.lang.String[] { "Name", "Topic", "Group", "Pull", "AutoAck", "AckTimeout", "PullMaxWaiting", "PendingMsgLimit", "PendingBytesLimit", "Endpoint", });
    org.mojolang.mojo.core.TimeProto.getDescriptor();
    io.ncraft.ncraft.messaging.PushEndpointProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
