// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/subscription.proto

package io.ncraft.ncraft.messaging;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ncraft.messaging.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string topic = 5;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 5;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>bool auto_ack = 6;</code>
   * @return The autoAck.
   */
  boolean getAutoAck();

  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 10;</code>
   * @return Whether the endpoint field is set.
   */
  boolean hasEndpoint();
  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 10;</code>
   * @return The endpoint.
   */
  io.ncraft.ncraft.messaging.PushEndpoint getEndpoint();
  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 10;</code>
   */
  io.ncraft.ncraft.messaging.PushEndpointOrBuilder getEndpointOrBuilder();
}
