// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/subscription.proto

package io.ncraft.ncraft.messaging;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_messaging_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_messaging_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#ncraft/messaging/subscription.proto\022\020n" +
      "craft.messaging\032$ncraft/messaging/push_e" +
      "ndpoint.proto\"~\n\014Subscription\022\014\n\004name\030\001 " +
      "\001(\t\022\r\n\005topic\030\005 \001(\t\022\r\n\005group\030\006 \001(\t\022\020\n\010aut" +
      "o_ack\030\t \001(\010\0220\n\010endpoint\030\n \001(\0132\036.ncraft.m" +
      "essaging.PushEndpointBp\n\032io.ncraft.ncraf" +
      "t.messagingB\021SubscriptionProtoP\001Z=github" +
      ".com/ncraft-io/ncraft/go/pkg/ncraft/mess" +
      "aging;messagingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.ncraft.ncraft.messaging.PushEndpointProto.getDescriptor(),
        });
    internal_static_ncraft_messaging_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_messaging_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_messaging_Subscription_descriptor,
        new java.lang.String[] { "Name", "Topic", "Group", "AutoAck", "Endpoint", });
    io.ncraft.ncraft.messaging.PushEndpointProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
