// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/messaging/subscription.proto

package io.ncraft.ncraft.messaging;

public interface SubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ncraft.messaging.Subscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string topic = 5;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 5;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string group = 6;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 6;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>bool pull = 7;</code>
   * @return The pull.
   */
  boolean getPull();

  /**
   * <code>bool auto_ack = 9;</code>
   * @return The autoAck.
   */
  boolean getAutoAck();

  /**
   * <code>.mojo.core.Duration ack_timeout = 10;</code>
   * @return Whether the ackTimeout field is set.
   */
  boolean hasAckTimeout();
  /**
   * <code>.mojo.core.Duration ack_timeout = 10;</code>
   * @return The ackTimeout.
   */
  org.mojolang.mojo.core.Duration getAckTimeout();
  /**
   * <code>.mojo.core.Duration ack_timeout = 10;</code>
   */
  org.mojolang.mojo.core.DurationOrBuilder getAckTimeoutOrBuilder();

  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 15;</code>
   * @return Whether the endpoint field is set.
   */
  boolean hasEndpoint();
  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 15;</code>
   * @return The endpoint.
   */
  io.ncraft.ncraft.messaging.PushEndpoint getEndpoint();
  /**
   * <code>.ncraft.messaging.PushEndpoint endpoint = 15;</code>
   */
  io.ncraft.ncraft.messaging.PushEndpointOrBuilder getEndpointOrBuilder();
}
