// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/storage/object.proto

package io.ncraft.ncraft.storage;

public interface ObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ncraft.storage.Object)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string etag = 1;</code>
   * @return The etag.
   */
  java.lang.String getEtag();
  /**
   * <code>string etag = 1;</code>
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString
      getEtagBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.mojo.core.Timestamp last_modified = 3;</code>
   * @return Whether the lastModified field is set.
   */
  boolean hasLastModified();
  /**
   * <code>.mojo.core.Timestamp last_modified = 3;</code>
   * @return The lastModified.
   */
  org.mojolang.mojo.core.Timestamp getLastModified();
  /**
   * <code>.mojo.core.Timestamp last_modified = 3;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getLastModifiedOrBuilder();

  /**
   * <code>int64 size = 4;</code>
   * @return The size.
   */
  long getSize();

  /**
   * <code>.mojo.core.MediaType content_type = 5;</code>
   * @return Whether the contentType field is set.
   */
  boolean hasContentType();
  /**
   * <code>.mojo.core.MediaType content_type = 5;</code>
   * @return The contentType.
   */
  org.mojolang.mojo.core.MediaType getContentType();
  /**
   * <code>.mojo.core.MediaType content_type = 5;</code>
   */
  org.mojolang.mojo.core.MediaTypeOrBuilder getContentTypeOrBuilder();

  /**
   * <code>bytes content = 6;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
