// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncraft/storage/object.proto

package io.ncraft.ncraft.storage;

public final class ObjectProto {
  private ObjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ncraft_storage_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ncraft_storage_Object_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033ncraft/storage/object.proto\022\016ncraft.st" +
      "orage\032\032mojo/core/media_type.proto\032\024mojo/" +
      "core/time.proto\"\233\001\n\006Object\022\014\n\004etag\030\001 \001(\t" +
      "\022\013\n\003key\030\002 \001(\t\022+\n\rlast_modified\030\003 \001(\0132\024.m" +
      "ojo.core.Timestamp\022\014\n\004size\030\004 \001(\003\022*\n\014cont" +
      "ent_type\030\005 \001(\0132\024.mojo.core.MediaType\022\017\n\007" +
      "content\030\006 \001(\014Bd\n\030io.ncraft.ncraft.storag" +
      "eB\013ObjectProtoP\001Z9github.com/ncraft-io/n" +
      "craft/go/pkg/ncraft/storage;storageb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.MediaTypeProto.getDescriptor(),
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
        });
    internal_static_ncraft_storage_Object_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ncraft_storage_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ncraft_storage_Object_descriptor,
        new java.lang.String[] { "Etag", "Key", "LastModified", "Size", "ContentType", "Content", });
    org.mojolang.mojo.core.MediaTypeProto.getDescriptor();
    org.mojolang.mojo.core.TimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
